branch-defaults:
  default:
    environment: maincampaign-env-test
  master:
    environment: maincampaign-env-test
global:
  application_name: maincampaign
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
